version: "3"

services:
  erp-backend:
    build: .
    ports:
      - "8080:8080"
  # ERP-mysql:
    # image: mysql:8.0.23
    # volumes:
      # - ~/volumes/CSBX/ERP/mysql/:/var/lib/csbx/mysql/
    # environment:
      # - MYSQL_ROOT_PASSWORD=123456
      # - MYSQL_DATABASE=jsh_erp
    # # If you want to expose these ports outside your dev PC,
    # # remove the "127.0.0.1:" prefix
    # ports:
      # - 3320:3306
    # command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  # redis:
    # image: redis:latest
    # container_name: redis
    # restart: always
    # ports:
      # - "6379:6379"
    # volumes:
      # - ~/volumes/CSBX/ERP/redis/:/var/lib/csbx/redis/
